### ISSUE TITLE
PC-Sync cable not correctly connected

### ISSUE THREAD

**Issue by cyclops1982** [timelapseplus/TimelapsePlus-Firmware#24]
Hi,

Yesterday i was doing a timelapse and the photo's it took where not the correct timing. I ran a auto-config again and it turned out the PC-Sync cable was not connected correctly.
if you've run auto-setup with the pc sync cable, it seems to be required for bulb ramping, but if it's not connected, the bulb ramping malfunctions. Can the bulb ramping get a check to make sure the PC-sync cable is connected?

**Comment by elijahparker** [comment]
When a bulb ramp is running, there will be a little "s" at the top of the timing bar showing that it's reading the PC-sync info (this is updated after every shot).  The timing is supposed to work out for whether the Pc-sync is connected or not in the default configuration, but there's an option in Settings->Auxiliary that defines whether the PC-sync is required (allows lower bulb-min) or if it should work with and without.  Apart from validating the PC-sync signal during a shot, I don't think I can detect the presence of the cable like I can with the shutter port (I'll have to double-check the hardware docs for this).

**Comment by jreinholm** [comment]
Hello,

There is a way to disable bulb-ramping unless a PC-sync cable is connected. With: Settings -> Auxiliary -> Aux Port  set to “PC Sync In”, you would then set: Settings -> Auxiliary -> PC-Sync Mode to "Required", which which will only allow bulb-ramping mode to run only if the PC-Sync cable is connected and the device has been successfully Auto configured. Otherwise, you'll get an error message.

James

**Comment by cyclops1982** [comment]
thanks!

This device has so many options. I find myself constantly amazed :)
